### PR TITLE
Fix v2 build papercuts

### LINKED ISSUE #19: Built version only shows server error after update to 2.0
### What were you trying to do?

After updating nativephp to 2.01 i built the app with the php artisan native:build command.

### What happened?

After building and installing our app, running the application only shows a 500 server error.
Before updating it worked.

### How to reproduce the bug

Build an app with the build command and start the application.

### Debug Output

```
{
    "Environment": {
        "PHP": {
            "Version": "8.4.5",
            "Path": "C:\\Users\\User\\.config\\herd-lite\\bin\\php.exe"
        },
        "Laravel": {
            "Version": "12.34.0",
            "ConfigCached": false,
            "RoutesCached": false,
            "DebugEnabled": true
        },
        "Node": {
            "Version": "v22.17.1",
            "Path": "C:\\Program Files\\nodejs\\node.exe"
        },
        "NPM": {
            "Version": "10.9.2",
            "Path": "C:\\Program Files\\nodejs\\npm\r\nC:\\Program Files\\nodejs\\npm.cmd\r\nC:\\Users\\User\\AppData\\Roaming\\npm\\npm\r\nC:\\Users\\User\\AppData\\Roaming\\npm\\npm.cmd"
        },
        "OperatingSystem": "WINNT"
    },
    "NativePHP": {
        "Versions": {
            "nativephp/desktop": "2.0.0.0",
            "nativephp/php-bin": "1.1.1.0"
        },
        "Configuration": {
            "Provider": "App\\Providers\\NativeAppServiceProvider",
            "BuildHooks": {
                "Pre": [],
                "Post": []
            },
            "NotarizationEnabled": false,
            "AzureTrustedSigningEnabled": false,
            "CustomPHPBinary": false
        }
    }
}
```

```
file_get_contents(C:/Users/user/AppData/Local/Programs/application/resources/build/app/vendor/nativephp/desktop/resources/electron/electron-plugin/src/preload/livewire-dispatcher.js): Failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_get_contents(C:/Users/user/AppData/Local/Programs/application/resources/build/app/vendor/nativephp/desktop/resources/electron/electron-plugin/src/preload/livewire-dispatcher.js): Failed to open stream: No such file or directory at C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\nativephp\\desktop\\src\\Events\\LivewireDispatcher.php:40)
[stacktrace]
#0 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_get_conten...', 'C:\\\\Users\\\\user\\\\...', 40)
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->{closure:Illuminate\\Foundation\\Bootstrap\\HandleExceptions::forwardsTo():257}(2, 'file_get_conten...', 'C:\\\\Users\\\\user\\\\...', 40)
#2 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\nativephp\\desktop\\src\\Events\\LivewireDispatcher.php(40): file_get_contents('C:/Users/user/A...')
#3 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\nativephp\\desktop\\src\\Events\\LivewireDispatcher.php(14): Native\\Desktop\\Events\\LivewireDispatcher->handle(Object(Illuminate\\Foundation\\Http\\Events\\RequestHandled))
#4 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(488): Native\\Desktop\\Events\\LivewireDispatcher->{closure:Native\\Desktop\\Events\\LivewireDispatcher::register():13}(Object(Illuminate\\Foundation\\Http\\Events\\RequestHandled))
#5 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(315): Illuminate\\Events\\Dispatcher->{closure:Illuminate\\Events\\Dispatcher::makeListener():483}('Illuminate\\\\Foun...', Array)
#6 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php(295): Illuminate\\Events\\Dispatcher->invokeListeners('Illuminate\\\\Foun...', Array, false)
#7 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Foun...')
#8 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1220): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#9 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\public\\index.php(20): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#10 C:\\Users\\user\\AppData\\Local\\Programs\\application\\resources\\build\\app\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\resources\\server.php(23): require_once('C:\\\\Users\\\\user\\\\...')
#11 {main}
"}

```

### Which operating systems have you seen this occur on?

Windows

### Notes

_No response_

### PR DESCRIPTION
**Pull request by gwleuverink**
This PR fixes a several papercuts:

- [x] Livewire dispatcher is not bundled in final build
- [x] Published electron project should be included in final build
- [x] Initial install showed `NativePHP@v1.0.0` - updated to `nativephp@v2`

Fixes #19

### CODE REVIEW

File: src/Builder/Concerns/CopiesToBuildDirectory.php [hunk 1]
```diff
@@ -106,4 +107,17 @@ private function keepRequiredDirectories()
         $filesystem->dumpFile("{$buildPath}/storage/app/public/_native.json", '{}');
         $filesystem->dumpFile("{$buildPath}/storage/logs/_native.json", '{}');
     }
+
+    private function keepLivewireDispatcher()
```
Comment (PeteBishwhip) [inline src/Builder/Concerns/CopiesToBuildDirectory.php]: Just a suggestion, but to avoid a method for every file, perhaps this could be named `keepRequiredFiles()`, similar to `keepRequiredDirectories()` above and could accept an array of files to keep (also opens up a potential for config to allow users to specify others)

Comment (PeteBishwhip) [reply src/Builder/Concerns/CopiesToBuildDirectory.php]: I think with good testing it's safe to do. But if this is a quick patch-release to resolve blocking issues now, I'm okay with it.

I definitely think this should be revisited and it sounds like you have a plan to do so. All good from me.

**Comment by gwleuverink** [comment]
This PR was later superseded by the approach in https://github.com/NativePHP/desktop/pull/28
